# Generated by Django 4.2.5 on 2023-09-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0003_streamplatform_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamplatform",
            name="website",
            field=models.URLField(max_length=100),
        ),
    ]
