# Generated by Django 4.2.5 on 2023-09-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0006_review_review_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
